# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trendstory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trendstory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10trendstory.proto\",\n\x0cTrendRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\"\x1e\n\rTrendResponse\x12\r\n\x05story\x18\x01 \x01(\t2C\n\x11TrendStoryService\x12.\n\rGenerateStory\x12\r.TrendRequest\x1a\x0e.TrendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trendstory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRENDREQUEST']._serialized_start=20
  _globals['_TRENDREQUEST']._serialized_end=64
  _globals['_TRENDRESPONSE']._serialized_start=66
  _globals['_TRENDRESPONSE']._serialized_end=96
  _globals['_TRENDSTORYSERVICE']._serialized_start=98
  _globals['_TRENDSTORYSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
